---
abstract: 'Detect if a UNIX system is running as a virtual machine'
author:
  - "Dave O'Neill, <dmo@dmo.ca>"
  - "Dave O'Neill <dmo@roaringpenguin.com>"
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Spec: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0.82
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sys-Detect-Virtualization
no_index:
  directory:
    - inc
    - t
recommends:
  Parse::DMIDecode: 0.03
requires:
  Getopt::Long: 0
  POSIX: 0
  Pod::Usage: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.107
